name: Hello Arocasan

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
          mkdir test
          ls -a
